import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* <script
          src="https://cdn.jsdelivr.net/npm/@tollbit/magic-search@0.0.1/dist/bundle.min.js"
          type="text/javascript"
        /> */}
        <script src="http://localhost:9000/bundle.js" type="text/javascript" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}

export const dynamic = "force-dynamic";
